### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by scenaristeur** [NoelDeMartin/ramen#1]
Hi @NoelDeMartin .
 I think you should change login form : 
You fill the value with 'https' so the placeholder does not appear and we don't know if we should fill with webid or provider url . I first fill with my webid. 
When we clear the login form, the placeholder is too long and we don't even know what we have to type see pic. 
I think you should only put 'your identity provider' as placeholder. Or use a select as I do in https://scenaristeur.github.io/verse 

Login component here https://github.com/scenaristeur/verse/blob/main/src/components/Login.vue

![Screenshot_20211128-150809_Chrome](https://user-images.githubusercontent.com/4020744/143771521-87bd432b-530e-4b2e-b27f-a1afd405209b.jpg)

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening an issue!

Yeah, I'm still not sure what's the best way to communicate which url people should use to log in :(. I've always been reluctant to add a list of providers; because even if I have an option for a custom url I feel like it goes against the philosophy of Solid to promote some providers above others. And yet, it's probably the best UX for most people because they don't have to second-guess what to write... I still have to think about it.

In terms of implementation, "any" url they write should work, but the flexible nature of the algorithm may backfire. I think the canonical use-case is providing a webId that points to an `solid:oidcIssuer` in the profile, and that one should always work. But if the url is anything other than a webId, I use a couple of heuristics that should work most of the time.

For this application in particular I don't worry too much, because I don't expect non-developers or someone unfamiliar with Solid to use it anyways. But I also want to use it to showcase my "best practices". So once I settle on something, I'll come back to update it. I agree that the current approach of not showing the placeholder by default, and the placeholder being too long, are not great. But I don't think I'll bother changing it for now, for the reasons I just mentioned.

**Comment by scenaristeur** [comment]
It's up to you 😉.
I don't think there good or bad practice, we all try to explore the Solid ecosystem sharing our practices is the best way to go ahead, step by step. In a decentralized world, many options can leave together 👍

Ps. Thxs for the recipe
