### ISSUE TITLE
Unable to create Cookbook

### ISSUE THREAD

**Issue by uvdsl** [NoelDeMartin/ramen#2]
Hi,
I thought I play a little with this gem of an app - but I ran into the following problem...

Using NSS (solidweb.org), I logged in and tried to create a cookbook.
(Using CSS, I could not even login because there is no typeIndex by default, which I assume the app relies on... different issue, I guess...)

Upon creating a cookbook, I get a 500 Server Error:
Dev tools network tab shows a GET request with 404 response to `/cookbook/`, makes sense, does not exist yet.
Then, a PATCH request to `/cookbook/` resulting in the 500. I do not know if NSS changed behaviour for PATCH on non-existent resources.

Thought, I'd let you know. :)

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening an issue!

> (Using CSS, I could not even login because there is no typeIndex by default, which I assume the app relies on... different issue, I guess...)

If the type index doesn't exist, the app should create it, so maybe there's another problem. What version of CSS are you using? Last time I tested was using `3.0.0`, so maybe something changed since.

> Upon creating a cookbook, I get a 500 Server Error:
> Dev tools network tab shows a GET request with 404 response to /cookbook/, makes sense, does not exist yet.
> Then, a PATCH request to /cookbook/ resulting in the 500. I do not know if NSS changed behaviour for PATCH on non-existent resources.

I think this has to do with a problem I reported a while ago in NSS https://github.com/nodeSolidServer/node-solid-server/issues/1703

I didn't think about updating this app, but maybe I should have, thanks for the reminder :sweat_smile:.

In any case, at this point I'm focusing on finishing [my latest app](https://github.com/noeldemartin/umai). Once it's ready, I'm planning on updating all my apps with many improvements I've learned about making Solid Apps. But I'll leave this issue open until I do.

**Comment by uvdsl** [comment]
> Last time I tested was using 3.0.0, so maybe something changed since.

I think I am at `5.0.0`.

> In any case, at this point I'm focusing on finishing [my latest app](https://github.com/noeldemartin/umai).

Ah cool! Looking forward to it! :)

No worries, I was just tinkering around seeing what apps still work and what could be re-used.

**Comment by NoelDeMartin** [comment]
I have looked into this to see why it didn't work with CSS, and it had something to do with a change I made a while ago to one of the dependencies.

In a nutshell, before that update I assumed that user profiles were always writable. But [ESS recently made profiles read-only](https://github.com/solid/webid-profile/issues/40#issuecomment-1225831232), so now it's necessary to read the `foaf:isPrimaryTopicOf` triple* in order to find a writable profile. And since I was making unauthenticated requests to read the profile in this app, I didn't find any.

On that point, I did see the following error which gave me a clue. Didn't you get it as well?

> Error: Can't create type index without a writable profile document

In any case, it should be fixed now :). Since I updated the libraries as well, this should also fix the problem with NSS so I'm closing this issue. Feel free to reopen in case something's still wrong.

\* It seems this may not be as simple [as it sounds](https://github.com/solid/webid-profile/issues/81).
